
inverse_hsb_op.so: inverse_hsb_op.cpp
    TF_CFLAGS=`python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))'`
    TF_LFLAGS=`python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))'`
    g++ -std=c++11 -shared $prereq -o $target -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2

all:V: inverse_hsb_op.so

