
hsb_ops.so: hsb_ops.cpp
    TF_CFLAGS=`python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))'`
    TF_LFLAGS=`python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))'`
    g++ -std=c++11 -shared $prereq -o $target -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -g -O2

clean:V:
    rm -f hsb_ops.so

all:V: hsb_ops.so

