#!/bin/bash

# Polee is a julia program, but options that rely on environment variables. We
# use this shell script wrapper to extract those options and set the right
# variables before running the real program.

unused_args=()
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-gpu)
        export CUDA_VISIBLE_DEVICES=''
        shift
        ;;
        -t|--num-threads)
        export JULIA_NUM_THREADS="$2"
        shift
        shift
        ;;
        *)
        unused_args+=("$1")
        shift
        ;;
    esac
done

set -- ${unused_args[@]}

julia -e 'import Polee; Polee.main()'
